### PR TITLE
Add Git revision to page for version tracking

### PR DESCRIPTION
**Pull request by dylants**
In order to better track what version of the app is deployed, include the Git revision in the page.  Since it’s included in the `layout.server.view.html`, this will be available on all pages within the application.

### CODE REVIEW

**Comment by cdupoiron** [comment]
Could it be possible to add a "versioning suffix" to assets files thanks to the Git revision ? 
example : application-fe55e54.min.js

**Comment by dylants** [comment]
@cdupoiron Certainly, this would be also be a good way to cache-bust the minified assets (since the generated production assets would have unique names).  I'll include this in a subsequent commit within this pull request.

**Comment by dylants** [comment]
Updated the pull request to include versioning the production assets

**Comment by cdupoiron** [comment]
Thx Dylants, nice work ! I'll try to implement it tomorrow !

**Pull request merged**
